export const productDetails = {
    GET_PRODUCT_DETAILS: 'GET_PRODUCT_DETAILS',
    GET_PRODUCT_DETAILS_LOADED: 'GET_PRODUCT_DETAILS_LOADED',
    GET_PRODUCT_DETAILS_ERROR: 'GET_PRODUCT_DETAILS_ERROR',
    SAVE_PRODUCT_DETAILS:'SAVE_PRODUCT_DETAILS',
    SAVE_PRODUCT_DETAILS_SUCCESS:'SAVE_PRODUCT_DETAILS_SUCCESS',
    SAVE_PRODUCT_DETAILS_ERROR:'SAVE_PRODUCT_DETAILS_ERROR',
    PRODUCT_DETAILS_URL: 'http://localhost:3601/graphql'
}
